### ISSUE TITLE
Outline can't be hidden through the СanvasGroup

### ISSUE THREAD

**Issue by AAAYaKo** [TLabAltoh/Unity-SDF-UI-Toolkit#10]
How to reproduce:
1. Create an SDF Quad inside a Сanvas group
2. Change the alpha of the Canvas group

https://github.com/user-attachments/assets/e7c7b491-f6de-4e27-be8c-3c59a6e60e54

I need to be able to control the color of both fill and stroke together throw the vertex color. The color property in the image affects the colors of the vertexes and is modified by the canvas group.

I suggest the following:
1. Add a color property for the fill. And stop using the property from the picture for it.
2. Make the stroke and fill colors multiply by the vertex color.

**Comment by TLabAltoh** [comment]
Thanks for the suggestion. I modified sahder to override alpha with vertex alpha. The latest update fixed this problem.

<img src="https://github.com/user-attachments/assets/4b4f7c9b-0237-4c9b-ab48-cc4434377513" width="512"></img>

```.hlsl
// i.color <--- vertex color
shadowAlpha *= pow(shadowAlpha, _ShadowPower) * _ShadowColor.a * i.color.a;
outlineAlpha *= _OutlineColor.a * i.color.a;
graphicAlpha *= color.a;
```

**Comment by AAAYaKo** [comment]
Current Version broken
Uploading bandicam 2024-07-18 17-06-56-018.mp4…

**Comment by TLabAltoh** [comment]
Sorry for the inconvenience of my destructive bug. It's because I replaced the maskable graphics with my own implementation and then unexpectedly changed unity's default material and this caused a problem. Now a fixed version has been released and please update the package.

**Comment by AAAYaKo** [comment]
Outline now is not working as expected.
Now it's a 2nd filled layer not just a line. Because of this it's not possible to use fill with transparency.
Also, the stroke works as outside, which is not convenient when switching from the previous version. I think you should add a property of the line placement (Inside, Center, Outside)
And make the default mode Inside. This will simplify the migration and will work like figma.

Translated with DeepL.com (free version)
