### ISSUE TITLE
Outline is disabled, but edge of sprite hiden

### ISSUE THREAD

**Issue by AAAYaKo** [TLabAltoh/Unity-SDF-UI-Toolkit#21]
![image](https://github.com/user-attachments/assets/f2498574-0ad5-4fbd-af1e-5ac92aa99bcd)

![image](https://github.com/user-attachments/assets/abd7646a-6eea-414a-876a-cc6ccf3e1af7)

![image](https://github.com/user-attachments/assets/067a22cf-0695-4719-8d04-7228b99e32b3)

**Comment by TLabAltoh** [comment]
Thanks for letting me know. I forgot to consider the case when the outline is disabled when doing [shader variant optimization](https://github.com/TLabAltoh/Unity-SDF-UI-Toolkit/issues/13#issuecomment-2340324346). This issue should be fixed by bellow.

```cs
	if (m_outline && m_outlineWidth > 0)
	{
		_materialRecord.SetFloat(PROP_OUTLINE_WIDTH, m_outlineWidth);
		_materialRecord.SetColor(PROP_OUTLINE_COLOR, m_outlineColor);

		switch (m_outlineType)
		{
			case OutlineType.Inside:
				_materialRecord.SetFloat(PROP_SHADOW_BORDER, (m_shadowWidth - m_shadowDilate));
				_materialRecord.SetFloat(PROP_OUTLINE_BORDER, 0);
				_materialRecord.SetFloat(PROP_GRAPHIC_BORDER, -m_outlineWidth);
				break;
			case OutlineType.Outside:
				_materialRecord.SetFloat(PROP_SHADOW_BORDER, (m_shadowWidth - m_shadowDilate) + m_outlineWidth);
				_materialRecord.SetFloat(PROP_OUTLINE_BORDER, m_outlineWidth);
				_materialRecord.SetFloat(PROP_GRAPHIC_BORDER, 0);
				break;
		}
	}
	else
	{
		_materialRecord.SetFloat(PROP_OUTLINE_WIDTH, 0);
		_materialRecord.SetColor(PROP_OUTLINE_COLOR, m_fillColor);

		_materialRecord.SetFloat(PROP_SHADOW_BORDER, (m_shadowWidth - m_shadowDilate));
		_materialRecord.SetFloat(PROP_OUTLINE_BORDER, 0);
		_materialRecord.SetFloat(PROP_GRAPHIC_BORDER, 0);
	}
```

**Comment by AAAYaKo** [comment]
Patch for edge works, but I've noticed the same problem with masks

**Comment by AAAYaKo** [comment]
![image](https://github.com/user-attachments/assets/bac55501-1291-43a4-b4f5-596dfe203609)
![image](https://github.com/user-attachments/assets/6c396511-77c2-4105-9ea8-829c7ae28d0f)

**Comment by AAAYaKo** [comment]
Normal mask works correctly

**Comment by TLabAltoh** [comment]
I looked again at the shader (```FragmentOutput.hlsl```) and maybe the rect clipping implementation is not correct. I had multiplicated clipping mask in alpha output only. This causes bright color not to be clipped.

```hlsl
#ifdef UNITY_UI_CLIP_RECT
effects.a *= UnityGet2DClipping(i.worldPosition.xy, _ClipRect);
#endif
```

<img src="https://github.com/user-attachments/assets/779593eb-448a-4fc7-b72d-564dda48bb57" width="256"></img>


```hlsl
#ifdef UNITY_UI_CLIP_RECT
effects *= UnityGet2DClipping(i.worldPosition.xy, _ClipRect);
#endif
```

<img src="https://github.com/user-attachments/assets/bba00b9c-a277-4293-88b5-99f95b822ddc" width="256"></img>

<details><summary>Vertex shader</summary>

```hlsl
v2f vert(appdata v) {
    v2f o;
    UNITY_SETUP_INSTANCE_ID(v);
    UNITY_INITIALIZE_OUTPUT(v2f, o);
    UNITY_INITIALIZE_VERTEX_OUTPUT_STEREO(o);
    o.worldPosition = v.vertex;
    o.vertex = UnityObjectToClipPos(v.vertex);
    o.uv = v.uv;
    o.color = v.color;

    // This implementation is taken from Unity's build in shader UI-Default.shader.
    // https://unity.com/releases/editor/archive
    float2 pixelSize = o.vertex.w;
    pixelSize /= float2(1, 1) * abs(mul((float2x2)UNITY_MATRIX_P, _ScreenParams.xy));

    float4 clampedRect = clamp(_ClipRect, -2e10, 2e10);
    float2 maskUV = (v.vertex.xy - clampedRect.xy) / (clampedRect.zw - clampedRect.xy);

    o.mask = half4(v.vertex.xy * 2 - clampedRect.xy - clampedRect.zw, 0.25 / (0.25 * half2(_UIMaskSoftnessX, _UIMaskSoftnessY) + abs(pixelSize.xy)));

    return o;
}
```

</details>

```hlsl
#ifdef UNITY_UI_CLIP_RECT
half2 m = saturate((_ClipRect.zw - _ClipRect.xy - abs(i.mask.xy)) * i.mask.zw);
effects *= (m.x * m.y);
#endif
```

<img src="https://github.com/user-attachments/assets/c2f5e534-6ef6-4e9c-8279-521ff2b318f9" width="256"></img>
