### ISSUE TITLE
UI Batching Support 

### ISSUE THREAD

**Issue by AAAYaKo** [TLabAltoh/Unity-SDF-UI-Toolkit#8]
Current material can't batch.
It increases draw calls compared to regular images.
![image](https://github.com/TLabAltoh/Unity-SDF-UI-Toolkit/assets/69294541/7779ebec-665d-4c8d-806d-960a23406f9a)
![image](https://github.com/TLabAltoh/Unity-SDF-UI-Toolkit/assets/69294541/d6d56a42-ca55-4e7d-80bd-ac458c258084)

**Comment by TLabAltoh** [comment]
Hi AAAYako, Currently the material is instanced per sdf-ui component, so the material used by the image component in the sdf-ui is not shared between the sdf-ui. Perhaps this is why the sdf-ui is not batch rendered (batch rendering requires the game object to use the same material). So if you want to batch render, you need to create a ui with an image component, but without the sdf-ui component, and copy the sdf-ui material you want to batch render into that image component. But this solution is a bit tricky, so I will add a feature to clone the sdf-ui for batch rendering.

![image](https://github.com/TLabAltoh/Unity-SDF-UI-Toolkit/assets/121733943/621fd481-3657-427f-8090-4c271e1022ad)

**Comment by AAAYaKo** [comment]
https://github.com/AAAYaKo/Unity-SDF-UI-Toolkit/tree/material_registry_feature
Pease, check this branch
I implemented 2 experimental optimization features:
1) LateUpdate central registry for SDFUI: Reduces amount of Unity messages per frame
2) Central Material Registry: Prevents material modification more than once per frame, manages materials of all SDFUIs, creates shared materials to support batching, manages material assignment in dynamic, caches shaders and materials.

It should be useful for UIs that frequently use SDFUI. The first optimization saves CPU time and the second saves time on draw calls. I was a few commits behind the master, so I didn't do a PR. It might also be a good idea to test it additionally to search for bugs, just like with any other optimization.

**Comment by AAAYaKo** [comment]
![image](https://github.com/user-attachments/assets/991a0e1c-e5af-44ee-8568-0b037b311a35)

Maybe we should add dependencies to the package json?

**Comment by TLabAltoh** [comment]
I saw your optimization and it seems nice implementation that pool material in registry for sharing material between sdf-ui components that have same properties. Could you make a pull request for this optimization? I made new branch named ```material-registry```. I make some commit, but fix conflict manually is not difficult, so if you can, please make pull request for material-registry branch in you timing. I merge material-registry to master branch manually after that.

**Comment by AAAYaKo** [comment]
https://github.com/user-attachments/assets/2c307551-2318-40d5-8498-bba114839257
![image](https://github.com/user-attachments/assets/6c33397c-7f2d-4bae-80de-8edd41617024)
SDF Circle has a problem with mask.

**Comment by AAAYaKo** [comment]
Also, I think SDF Circle doesn't need radius property, instead use half of the shortest side of the rect.

**Comment by TLabAltoh** [comment]
Thanks for the info, this problem still remain in the latest commit ? recently, I changed for some maskable graphic’s part (so there is a possibility that this change caused a problem and because of my dirty commit log, I didn’t make notice for this update at any issue)

<video src="https://github.com/user-attachments/assets/146d6848-6a68-4186-9ba5-0ea0b2a13950"></video>

My latest commit for maskable graphics is here (commit yesterday)

- d7a5a416856c940507247e3c44aa00cd21f6e046
- 8cfcce4f5cf0cc6752cfdbc0823f54b9d24f2245
- 7b0dd7a12bede00142b080445224e98aba9535a5
- f7aa7f82f94e7bc93770166df49124bf84479f1e

**Comment by AAAYaKo** [comment]
Currently, I don`t see any problems.

**Comment by AAAYaKo** [comment]
SDF Ring, SDF Pie
![image](https://github.com/user-attachments/assets/c796ef1d-9560-4350-9a0a-9d7550f63a52)

When antialiasing is enabled, they have a 1 pixel line.
