### ISSUE TITLE
Shadows and anti-aliasing

### ISSUE THREAD

**Issue by AAAYaKo** [TLabAltoh/Unity-SDF-UI-Toolkit#9]
Add shadows and anti-aliasing as in this project.
https://github.com/BlenMiner/Unity-UI-SDF?tab=readme-ov-file

**Comment by TLabAltoh** [comment]
Hi, I looked at the recommended project you attached and it seems pretty nice. I will merge it. But maybe it will take some time to replace the mask implementation from the current depending and please note it.

**Comment by AAAYaKo** [comment]
If it is possible, it would be awesome to add the ability to offset shadow by x y.

**Comment by AAAYaKo** [comment]
The shadow doesn't ignore outline, what can be a problem for shaped figures.

**Comment by TLabAltoh** [comment]
There are not complete but some updates. I have added shadow offset and some outline update (currently only inside and outside outline).

[shadow offset and some outline update (youtube)](https://youtu.be/IbbOAeVePhk)

**Comment by AAAYaKo** [comment]
![image](https://github.com/user-attachments/assets/42573dee-4245-45ca-a7c2-a11209a2691b)
If shadow is off, it is not needed to take it into account when calculating vertexes. SDF is a pixel shader, extra empty space will negatively affect performance.

**Comment by AAAYaKo** [comment]
Implemented in #11

**Comment by TLabAltoh** [comment]
<img src="https://github.com/user-attachments/assets/04aeeeee-3445-4a1a-8af7-0c297ba32455" width="512"></img>

This update, I updated the sdf-ui component to inherit the raw-image component to be able to use the same property of raw-image and to be able to use texture directly. (and to merge the quad shape inspector implementation into the other shape ui).

**Comment by AAAYaKo** [comment]
I see, but that's not exactly what I meant. I used RawImage only in specific cases, most of the icons are sprites. We can't do away with sprites because we use SpriteAtlas, which generates the texture and uv. For the few specific cases we don't want to lose compatibility with the entire project.

**Comment by AAAYaKo** [comment]
![image](https://github.com/user-attachments/assets/6e7f6abc-79d1-40b8-bb9b-3000c5b981d4)
Rename file from Default Script Name to Class Name

**Comment by AAAYaKo** [comment]
![image](https://github.com/user-attachments/assets/07be5385-3675-4910-bf36-b43dace7f623)
When you enter Play Mode in the prefab editor, the image display is missing.

**Comment by AAAYaKo** [comment]
![image](https://github.com/user-attachments/assets/9d9da95d-675f-4359-83cc-1232a558c357)
For clarity, I think it's worth rename main color to fill color.

**Comment by AAAYaKo** [comment]
The shadow should not change offset by rotation, like in figma. This is needed for animations.
https://github.com/user-attachments/assets/44e9522e-fcc9-4315-9234-aaddeb233d33

**Comment by AAAYaKo** [comment]
https://github.com/user-attachments/assets/9487de6a-eee3-4f25-85ba-7bc3a60ee0dc

Implemented in #12

**Comment by TLabAltoh** [comment]
<video src="https://github.com/user-attachments/assets/68a7f9bd-a265-4f0e-95c0-937ebd559405"></video>

I added option to switch sprite and texture which type of image we want to use. And for sprite, add atlus support.

Currently, the problem of missing image display when entering play mode from the prefab editor is still there (in my case, entering play mode with ignoring "exit edit mode" and exiting play mode to return to edit mode causes a similar problem. I'm working on it).

**Comment by AAAYaKo** [comment]
I think switching to custom maskable graphics is the right decision. Right now, standard image doesn't work well with rotation either, so I don't think it's a problem.
